import { GetInformationFromSapienForSamirController } from './GetInformationFromSapienForSamirController';
import { GetInformationFromSapienForSamirUseCase } from './GetInformationFromSapienForSamirUseCase';
import { GetInformationFromSapienForSamirControllerSemIdade } from './GetInformationFromSapienForSamirControllerSemIdade';
import { GetInformationFromSapienForSamirUseCaseSemIdade } from './GetInformationFromSapienForSamirUseCaseSemIdade';

const getInformationFromSapienForSamirUseCase = new GetInformationFromSapienForSamirUseCase();
const getInformationFromSapienForSamirController = new GetInformationFromSapienForSamirController(getInformationFromSapienForSamirUseCase);


const getInformationFromSapienForSamirUseCaseSemIdade = new GetInformationFromSapienForSamirUseCaseSemIdade();
const getInformationFromSapienForSamirControllerSemIdade = new GetInformationFromSapienForSamirControllerSemIdade(getInformationFromSapienForSamirUseCaseSemIdade);

export {getInformationFromSapienForSamirUseCase, getInformationFromSapienForSamirController, getInformationFromSapienForSamirUseCaseSemIdade, getInformationFromSapienForSamirControllerSemIdade };